export const MEAL_FILTERS=[
    {title:'breakfast',Icon:require('../../../Assets/Images/breakfast.png')},
    {title:'brunch',Icon:require('../../../Assets/Images/brunch.png')},
    {title:'lunch',Icon:require('../../../Assets/Images/lunch.png')},
    {title:'dinner',Icon:require('../../../Assets/Images/Dinner.png')},
    {title:'snack',Icon:require('../../../Assets/Images/candies.png')},
    {title:'teatime',Icon:require('../../../Assets/Images/Tea.png')},
];
export const DIET_FILTERS = [
    'balanced',
    'high-fiber',
    'high-protein',
    'low-carb',
    'low-fat',
    'low-sodium',
  ];
  export const HEALTH_FILTERS = [
    'alcohol-cocktail',
    'alcohol-free',
    'celery-free',
    'crustacean-free',
    'dairy-free',
    'DASH',
    'egg-free',
    'fish-free',
    'fodmap-free',
    'gluten-free',
    'immuno-supportive',
    'keto-friendly',
    'kidney-friendly',
    'kosher',
    'low-potassium',
    'low-sugar',
    'lupine-free',
    'Mediterranean',
    'mollusk-free',
    'mustard-free',
    'No-oil-added',
    'paleo',
    'peanut-free',
    'pecatarian',
    'pork-free',
    'red-meat-free',
    'sesame-free',
    'shellfish-free',
    'soy-free',
    'sugar-conscious',
    'sulfite-free',
    'tree-nut-free',
    'vegan',
    'vegetarian',
    'wheat-free',
  ];
 
  
  export const DISH_FILTERS = [
    'alcohol cocktail',
    'biscuits and cookies',
    'bread',
    'cereals',
    'condiments and sauces',
    'desserts',
    'drinks',
    'egg',
    'ice cream and custard',
    'main course',
    'pancake',
    'pasta',
    'pastry',
    'pies and tarts',
    'pizza',
    'preps',
    'preserve',
    'salad',
    'sandwiches',
    'seafood',
    'side dish',
    'soup',
    'special occasions',
    'starter',
    'sweets',
  ];
  export const CUISINE_FILTERS = [
    'american',
    'british',
    'caribbean',
    'central europe',
    'chinese',
    'eastern europe',
    'french',
    'greek',
    'indian',
    'italian',
    'japanese',
    'korean',
    'kosher',
    'mediterranean',
    'mexican',
    'middle eastern',
    'nordic',
    'south american',
    'south east asian',
    'world',
  ];   